# Enable APIServerTracing
# ref: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/647-apiserver-tracing
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: v1.22-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.22.0
  extraMounts:
  - hostPath: ./trace-configuration.yaml
    containerPath: /etc/kubernetes/trace-configuration.yaml
featureGates:
  APIServerTracing: true
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        tracing-config-file: /etc/kubernetes/trace-configuration.yaml
      extraVolumes:
      - name: trace-configuration
        hostPath: /etc/kubernetes/trace-configuration.yaml
        mountPath: /etc/kubernetes/trace-configuration.yaml
        readOnly: true
        pathType: FileOrCreate
