# Enable APIServerTracing
# ref: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/647-apiserver-tracing
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: v1.22-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.22.0
  extraMounts:
  - hostPath: ./trace-configuration.yaml
    containerPath: /etc/kubernetes/trace-configuration.yaml
featureGates:
  APIServerTracing: true
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        tracing-config-file: /etc/kubernetes/trace-configuration.yaml
      extraVolumes:
      - name: trace-configuration
        hostPath: /etc/kubernetes/trace-configuration.yaml
        mountPath: /etc/kubernetes/trace-configuration.yaml
        readOnly: true
        pathType: FileOrCreate
---
# ref: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/apiserver/v1alpha1/types.go#L154-L169 
#
#// TracingConfiguration provides versioned configuration for tracing clients.
#type TracingConfiguration struct {
#	metav1.TypeMeta `json:",inline"`
#
#	// +optional
#	// Endpoint of the collector that's running on the control-plane node.
#	// The APIServer uses the egressType ControlPlane when sending data to the collector.
#	// The syntax is defined in https://github.com/grpc/grpc/blob/master/doc/naming.md.
#	// Defaults to the otlpgrpc default, localhost:4317
#	// The connection is insecure, and does not support TLS.
#	Endpoint *string `json:"endpoint,omitempty" protobuf:"bytes,1,opt,name=endpoint"`
#
#	// +optional
#	// SamplingRatePerMillion is the number of samples to collect per million spans.
#	// Defaults to 0.
#	SamplingRatePerMillion *int32 `json:"samplingRatePerMillion,omitempty" protobuf:"varint,2,opt,name=samplingRatePerMillion"`
#}
#
#apiVersion: apiserver.config.k8s.io/v1alpha1
#kind: TracingConfiguration
#name: telemetory
#endpoint: "http://hogehoge"
#samplingRatePerMillion: 0
